In [61]:
import pandas as pd

In [63]:
windspeed = pd.read_excel(r"C:\Users\mrmik\OneDrive\Desktop\NSS\Python\Projects\Cycling_Capstone\notebooks\windspeed_df.xlsx")

In [65]:
baseline = pd.read_excel(r"C:\Users\mrmik\OneDrive\Desktop\NSS\Python\Projects\Cycling_Capstone\notebooks\baseline_data.xlsx")

In [67]:
merged = pd.merge(windspeed, baseline[['Race Name', 'Year', 'Winner Time', 'Avg Speed (km/h)']],
    on=['Race Name', 'Year'],
    how='left'
)

In [69]:
merged.to_excel('wind_and_winner.xlsx')

In [71]:
windspeed2 = pd.read_excel(r"C:\Users\mrmik\OneDrive\Desktop\NSS\Python\Projects\Cycling_Capstone\notebooks\wind_and_winner.xlsx")

In [73]:
windspeed2.isnull()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Race Name,Year,Index,Latitude,Longitude,Windspeed_kmh,Wind_direction,Cardinal_direction,Winner Time_x,Winner Time_y,Avg Speed (km/h)
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,True,False,False
299,False,False,False,False,False,False,False,False,False,False,False,True,False,False
300,False,False,False,False,False,False,False,False,False,False,False,True,False,False
301,False,False,False,False,False,False,False,False,False,False,False,True,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [75]:
merged2 = pd.merge(windspeed2, baseline[['Race Name', 'Year', 'Winner Time', 'Avg Speed (km/h)']],
    on=['Race Name', 'Year'],
    how='left'
)

In [77]:
merged2.isnull()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Race Name,Year,Index,Latitude,Longitude,Windspeed_kmh,Wind_direction,Cardinal_direction,Winner Time_x,Winner Time_y,Avg Speed (km/h)_x,Winner Time,Avg Speed (km/h)_y
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [79]:
merged.to_excel('wind_and_winner2.xlsx')